(def-frame living-thing nil (extendable t propagate t)
   breathes (value 'yes)
   eats regularly)
(def-frame person (living-thing) (extendable t propagate t if-added foo)
   legs (value 2)
   talks (value 'yes))
(setq p1 (make-person 'p1 :talks '(value no)))
(def-frame child (person) (extendable t propagate t)
   talks (value 'no)
   works (value 'no))
(setq child1 (make-child 'child1 :talks '(value yes)))
(def-frame diversion () (extendable t)
   fun (value 'usually))
(def-frame baby (person diversion) (extendable t)
   cries (value 'sometimes))
(setq b1 (make-baby 'baby1 :cries '(value always)))
